// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-sdk-go-v2/service/rds

package mocks

import (
	context "context"
	reflect "reflect"

	rds "github.com/aws/aws-sdk-go-v2/service/rds"
	gomock "github.com/golang/mock/gomock"
)

// MockRDSClient is a mock of RDS Client interface.
type MockRDSClient struct {
	ctrl     *gomock.Controller
	recorder *MockRDSClientMockRecorder
}

// MockRDSClientMockRecorder is the mock recorder for MockRDSClient.
type MockRDSClientMockRecorder struct {
	mock *MockRDSClient
}

// NewMockRDSClient creates a new mock instance.
func NewMockRDSClient(ctrl *gomock.Controller) *MockRDSClient {
	mock := &MockRDSClient{ctrl: ctrl}
	mock.recorder = &MockRDSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRDSClient) EXPECT() *MockRDSClientMockRecorder {
	return m.recorder
}

// CreateDBInstance mocks base method.
func (m *MockRDSClient) CreateDBInstance(ctx context.Context, params *rds.CreateDBInstanceInput, optFns ...func(*rds.Options)) (*rds.CreateDBInstanceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateDBInstance", varargs...)
	ret0, _ := ret[0].(*rds.CreateDBInstanceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDBInstance indicates an expected call of CreateDBInstance.
func (mr *MockRDSClientMockRecorder) CreateDBInstance(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDBInstance", reflect.TypeOf((*MockRDSClient)(nil).CreateDBInstance), varargs...)
}

// DeleteDBInstance mocks base method.
func (m *MockRDSClient) DeleteDBInstance(ctx context.Context, params *rds.DeleteDBInstanceInput, optFns ...func(*rds.Options)) (*rds.DeleteDBInstanceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteDBInstance", varargs...)
	ret0, _ := ret[0].(*rds.DeleteDBInstanceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDBInstance indicates an expected call of DeleteDBInstance.
func (mr *MockRDSClientMockRecorder) DeleteDBInstance(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDBInstance", reflect.TypeOf((*MockRDSClient)(nil).DeleteDBInstance), varargs...)
}

// DescribeDBInstances mocks base method.
func (m *MockRDSClient) DescribeDBInstances(ctx context.Context, params *rds.DescribeDBInstancesInput, optFns ...func(*rds.Options)) (*rds.DescribeDBInstancesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeDBInstances", varargs...)
	ret0, _ := ret[0].(*rds.DescribeDBInstancesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeDBInstances indicates an expected call of DescribeDBInstances.
func (mr *MockRDSClientMockRecorder) DescribeDBInstances(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDBInstances", reflect.TypeOf((*MockRDSClient)(nil).DescribeDBInstances), varargs...)
}

// ModifyDBParameterGroup mocks base method.
func (m *MockRDSClient) ModifyDBParameterGroup(ctx context.Context, params *rds.ModifyDBParameterGroupInput, optFns ...func(*rds.Options)) (*rds.ModifyDBParameterGroupOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ModifyDBParameterGroup", varargs...)
	ret0, _ := ret[0].(*rds.ModifyDBParameterGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModifyDBParameterGroup indicates an expected call of ModifyDBParameterGroup.
func (mr *MockRDSClientMockRecorder) ModifyDBParameterGroup(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyDBParameterGroup", reflect.TypeOf((*MockRDSClient)(nil).ModifyDBParameterGroup), varargs...)
}

// RebootDBInstance mocks base method.
func (m *MockRDSClient) RebootDBInstance(ctx context.Context, params *rds.RebootDBInstanceInput, optFns ...func(*rds.Options)) (*rds.RebootDBInstanceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RebootDBInstance", varargs...)
	ret0, _ := ret[0].(*rds.RebootDBInstanceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RebootDBInstance indicates an expected call of RebootDBInstance.
func (mr *MockRDSClientMockRecorder) RebootDBInstance(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebootDBInstance", reflect.TypeOf((*MockRDSClient)(nil).RebootDBInstance), varargs...)
}
